name: dingo_simulator_ci

on: [push, pull_request]

jobs:

  # dingo_simulator_noetic_ci:
  #   name: Noetic 
  #   strategy:
  #     matrix:
  #       env:
  #         - {ROS_DISTRO: noetic, ROS_REPO: main}
  #         - {ROS_DISTRO: noetic, ROS_REPO: testing}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: 'ros-industrial/industrial_ci@master'
  #       env: ${{matrix.env}}

  dingo_simulator_melodic_ci:
    name: Melodic
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic, ROS_REPO: main}
          - {ROS_DISTRO: melodic, ROS_REPO: testing}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}